version: '3'

services:
  listen-log:
    build:
      dockerfile: 'listen-log/Dockerfile'
      context: '.'

    command:
      './listen-log -p 25555'

    network_mode: host
    ports:
      - 25555

  send-log:
    build:
      dockerfile: 'send-log/Dockerfile'
      context: '.'
    
    network_mode: host
    ports:
      - 25555

    command:
      './send-log -f file.log -h localhost:25555'

    depends_on:
      - listen-log